### PR TITLE
GPS & EMG Filter

### PR DESCRIPTION
**Pull request by npostans**
I've updated the GPS documentation and also uploaded code for an EMG filter

### CODE REVIEW

**Review by dblana — CHANGES_REQUESTED** [review]
Hi Neil, two requests before I merge your changes:
- Your Gait_profile_score folder appears to only contain Gait_profile_score.md. What happened to the three original files? (The python code, csv example and GPS v1.4 readme.md)
- Could you put the EMG HP Filter folder inside the Code folder?

Thank you! :star2:

**Comment by npostans** [comment]
Hi Dimitra,

I've moved the filter code (after a couple of aborted attempts!), but I don't know what happened to the other GPS files. I wonder if I synced my folder with the main one after things had been moved and I ended up with an empty folder. I think it happened around the time of the original pull request, but I wasn't sure if this was normal. I'll try temporarily moving the .md file in my fork and then resyncing with the master to get all the files back and then moving the .md file back in with them.

**Comment by npostans** [comment]
@dblana 
On second thoughts, will that wipe out my filter folder too? I don't want to sync things and lose what I've done. Is there a better way to do this?
Thanks, Neil.

**Comment by dblana** [comment]
Ok, give me a few days @npostans and I'll sort it out! :smiley:

**Comment by npostans** [comment]
Thanks @dblana. Let me know if you need me to create another pull request.

**Comment by dblana** [comment]
Hi @npostans ! I added your files myself to make sure you don't lose any of them. So there is no need for another pull request, but make sure you sync your fork to the open-code repository. If you use Git, you can follow [these instructions](https://help.github.com/en/articles/merging-an-upstream-repository-into-your-fork), but if you just want to do it via the browser, see how to do it [here](https://github.com/KirstieJane/STEMMRoleModels/wiki/Syncing-your-fork-to-the-original-repository-via-the-browser). 

In general, before you make any new changes to your fork, make sure it is synced to the open-code repository. I need to add these instructions to the [contributing guidelines](https://github.com/cmasuki/open-code/blob/master/CONTRIBUTING.md)... :grimacing: 

Thank you very much for your patience! We are learning how all this works together :smile:

**Pull request closed without merging**
