### PR TITLE
anonymisation functions

### PR DESCRIPTION
**Pull request by aaa34169**
Here are a python and matlab functions for changing name of the subject with in the c3d file. 
I hope @CarolineORLAUKeele  is happy 

The matlab script is from Stephane Armand at Geneva (Switzerland) and i implemented the python script. 

I could make the python script more convenient. Let me know. 
So far, you have to open the python script in a python editor (spyder, pycharm ....), edit the c3d name and run the py file. 

What i could do it s to avoid opening any python IDE and make the script run from a DOS-console but i know it s a bit reluctant for non programmer 

cheers 

Fabien

### CODE REVIEW

**Comment by dblana** [comment]
Hi Fabien,

Thank you for this! A few questions / requests:

- Could you change all .readme files to have markdown (.md) extensions? You can include "readme" in the file name (e.g. anonymiseC3D_readme.md). Otherwise markdown is not rendered correctly. (For example: I renamed your btk readme file from [this](https://github.com/aaa34169/open-code/blob/master/Code/c3d%20IO/Biomechanical%20toolkit%20(Btk)/btk.readme) to [this](https://github.com/cmasuki/open-code/blob/master/Code/c3d%20IO/Biomechanical%20toolkit%20(Btk)/btk_README.md).)

- Could you add some instructions for installing btk for Matlab (in the [same readme file](https://github.com/cmasuki/open-code/blob/master/Code/c3d%20IO/Biomechanical%20toolkit%20(Btk)/btk_README.md))? Otherwise people won't know how to do this to use the matlab code for anonymising C3D files...

- About the Matlab code: since you didn't write it, have you tested that it works? And is Stephane Armand happy to share it with the CMAS community?

- Does your Python code for anonymising C3D files require Nexus? This is what I understand from [here](https://pycgm2.github.io/pages/pyCGM2Installation), but it's not listed as a requirement in your readme file.

Thanks again for being our top contributor :+1: :100:

**Comment by carolinestewart** [comment]
Hi Fabien,
You're right - I'm happy!  I'm really keen to try the Python version.  Is it ready to go?  Please could you let me know when it's in the repository and how to find it (sorry if this is an obvious question - I'm new to this game).
Caroline

**Comment by dblana** [comment]
Hi Caroline, Fabien has submitted a pull request, but I've asked him to make a few changes before I merge his code... If you'd like to review his code yourself (please do!), you can see it here (this is Fabien's fork of our repository): https://github.com/aaa34169/open-code/tree/master/Code/anonymising%20c3d

**Comment by carolinestewart** [comment]
Hi Fabien, at the moment it looks like this code is dependent on pyCGM2.  We're keen to test your new CGM2 code but it would be good if the anonymiser was standalone.  Is that possible?  I suspect it will prove quite popular and the link to CGM2 might put people off ...?  Also you specify Python 2.7 and I'm on 3.5 at the moment.  Is that an issue?  Lastly, sometimes you need to clear the whole path, rather than just the subject name.  Is that possible too?

Sorry to ask lots of tricky questions - please interpret this as enthusiasm!

**Comment by dblana** [comment]
Since Python 2.x will not be supported at all from 2020, it would be good to stick with Python 3...

**Comment by aaa34169** [comment]
Hello Caroline

So, we are 2 enthusiasts. :-)
More technically, my code is dependant on Btk and i  implemented high-level functions overloading BTK in pyCGM2.
Installation of dependency ( btk or pyCGM2) is the only thing that could put people off. Most of time in python, installation needs to open a dos-console and type command that make people reluctant.  I know.
That why, i tried to make installation of pyCGM2 easy ( download the code and double click on installer.bat)

By the way, pyCGM2 will be embedded in Nexus 2.9 so that could facilitate installation and parallel use of python 3 and 2

What i could propose is to create a script that could be recognize as a  windows command. That mean if you want to anonymise a c3d, you would have to open a console pointing to your session folder and type a command like:
```anonymise gait.c3d ```

About python 3 !!!
I am sure either at Keele or Oswestry, i could find a PC under window XP :-p
Don t panic with the support ending

anyway ,
My package is only compatible python2.7 because Btk and nexus API were compiled in python2. 
Compatibility with python3 is planed of course. I have my own version of btk in python3.7. That a good start.

Fabien

**Review by dblana — CHANGES_REQUESTED** [review]
Fabien, did you see my comment about a week ago? Please have a look at my questions so I can merge your changes :smiley:

**Comment by aaa34169** [comment]
Hi Dimitra

I have modified my fork with according your comments

 1 . _Could you change all .readme files to have markdown (.md) extensions? You can include "readme" in the file name (e.g. anonymiseC3D_readme.md)._

Done :smiley:

 2. _Could you add some instructions for installing btk for Matlab (in the same readme file)? Otherwise people won't know how to do this to use the matlab code for anonymising C3D files..._

done also. i update the btk.md file. i  

 3. _About the Matlab code: since you didn't write it, have you tested that it works? And is Stephane Armand happy to share it with the CMAS community?_

Of course, Stephane is a really open-minded and collaborative person. I had his approval

 4. _Does your Python code for anonymising C3D files require Nexus? This is what I understand from here, but it's not listed as a requirement in your readme file_

No.  In the last version of pyCGM2, my installer install nexus-formatted pipeline and other vicon files if an only if Nexus is detected on the computer. 

You re right Updating my  my website would be a good idea  :smirk:

**Review by dblana — CHANGES_REQUESTED** [review]
I don't see these changes in your master branch... :thinking:

**Comment by aaa34169** [comment]
sorry, i did it my development branch. I v s just merge it with Master :-)

**Pull request merged**
